#workflow_dispatch: # this adds a run button
# Steps represent a sequence of tasks that will be executed as part of the job
steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Scan
    - name: Checkmarx DAST Github Action
      uses: Checkmarx/dast-github-action@v1.0.0-beta
      env:
        CX_APIKEY: ${{ secrets.CX_ONE_API_KEY }}
      with:
        command: "web"
        config: 'zap_config.yaml'
        base_url: "localhost.cxast.net"
        environment_id: "c608a51a-ec4e-4eef-81c4-a0241737efd7"
        fail_on: "HIGH"
        verbose: true
